### ISSUE TITLE
[Bug]: Quest add item UI crashing.

### ISSUE THREAD

**Issue by TheAngel7** [FTBTeam/FTB-Mods-Issues#1182]
### Mod

FTB Quests

### Mod version

2001.4.3

### Forge / Fabric version

Forge 47.2.32

### What issue are you having?

when adding item as a request and setting amount using the provided number slot it changes to air, if you try changing it again your game may crash.

### Crashlogs

https://pste.ch/ucehegitus.rb

### Steps to reproduce

1. create new quest.
2. add item as quest request.
3. set it to dirt (for example)
4. set amount to any number high number (tested it few times, results wary for some reason, if it turns to air it will crash if you try editing it)
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/61cd4715-89c3-42fa-ab3e-7e78f81a8c8b)
Image for reference.
5. confirm.
6. watch it turn air.
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/fbef45a8-3923-4acf-8740-fd823cfe978a)
7. trying to change it may crash the game.

### Anything else to note?

Happened on my own modpack (4.22)
https://www.curseforge.com/minecraft/modpacks/die-hard-forest

I was also using special mod that doesn't actually crash my game when a crash happens (let's me return to menu instead)

**Comment by TheAngel7** [comment]
It seems to happen at random?

The issue is easily avoidable if I just won't change the number, but a bug is a bug, and since I got hang of reporting bugs I might as well do it.

**Comment by TheAngel7** [comment]
the second crash I triggered
https://pste.ch/akamaqenim.rb

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 2001.4.4 release

**Comment by TheAngel7** [comment]
Actually, it's still not fixed
https://pste.ch/funixigefa.pl
![image](https://github.com/FTBTeam/FTB-Mods-Issues/assets/170236510/8df328f3-7306-4294-b8c3-c00f4b24dca0)

**Mod version**
2001.4.4

**Comment by TheAngel7** [comment]
I tried adding 128 rotten flesh to the quest

**Comment by desht** [comment]
Hmm, yeah, you're right. I'll continue to look at this. Think I know what's happening here...

**Comment by desht** [comment]
So yeah this will be _properly_ fixed in the next release, coming out today.  The reason is that is got missed in testing the previous fix is due to the stack size being encoded (by vanilla) as a byte when it's sent to the server, with a 50% chance of a negative size.  Negative-sized stack are always considered empty, hence the stack's item appearing as Air (even though the size is sent separately).

When I tested, I used an arbitrary stack size which encoded to a positive value, so I didn't see the problem...
