### ISSUE TITLE
[Bug]: [1.18+] FTB Ultimine and Tetra cannot ultimine when `require_tool` is set to true in config

### ISSUE THREAD

**Issue by Saereth** [FTBTeam/FTB-Mods-Issues#336]
### Mod

FTB Ultimine

### Mod version

`ftb-ultimine-forge-1802.3.3-build.55`

### Forge / Fabric version

`40.1.45`, `40.1.68`

### Modpack & version

FTB Inferno 0.1.3, Enigmatica 8 2.1.0

### What issue are you having?

![image](https://user-images.githubusercontent.com/9200909/177002599-ee6f9098-ab74-4919-843e-e3e17142de20.png)

Setting required tool to true and tagging Tinkers and Tetra tools results in them still not being allowed to ultimine with.

After doing some testing, trying to add all possible tags to a tinkers pickaxe, I still fail to get it to ultimine
tags tested and none of these worked:

- `ftbultimine:tools`
- `ftbultimine:allowedtools`
- `ftbultimine:included_tools`

Tetra tools also cannot be used to Ultimine, despite having the tags above. Please see this issue for all of the context :D
https://github.com/EnigmaticaModpacks/Enigmatica8/issues/182

### Crashlogs

N/A

### Steps to reproduce

1. Set `require_tool` to `true` in config
2. Add tags to tinkers pickaxe or tetra tool
3. Fail to ultimine

### Anything else to note?

N/A

**Comment by MichaelHillcox** [comment]
Fixed and shipped for 1.18 + 1.19

**Comment by MichaelHillcox** [comment]
I'm not sure what you mean by this, the fabric mod received the update at the same time, if the modpack hasn't updated yet, you'll want to ask them to update the mod

**Comment by EvanHsieh0415** [comment]
I have tried to update myself to the latest version to fix this error, but it still doesn't work

**Comment by EvanHsieh0415** [comment]
> I'm not sure what you mean by this, the fabric mod received the update at the same time, if the modpack hasn't updated yet, you'll want to ask them to update the mod

@MichaelHillcox I have tried to update FTB Ultimine and Hephaestus (Tinker's Construct Quilt version) to the latest version, but FTB Ultimine still does not work on Tinker's tools.

**Comment by GGG-KILLER** [comment]
> > I'm not sure what you mean by this, the fabric mod received the update at the same time, if the modpack hasn't updated yet, you'll want to ask them to update the mod
> 
> @MichaelHillcox I have tried to update FTB Ultimine and Hephaestus (Tinker's Construct Quilt version) to the latest version, but FTB Ultimine still does not work on Tinker's tools.

Probably very related but I've opened #512 due to the same issue you're mentioning

**Comment by EvanHsieh0415** [comment]
> > > I'm not sure what you mean by this, the fabric mod received the update at the same time, if the modpack hasn't updated yet, you'll want to ask them to update the mod
> > 
> > 
> > @MichaelHillcox I have tried to update FTB Ultimine and Hephaestus (Tinker's Construct Quilt version) to the latest version, but FTB Ultimine still does not work on Tinker's tools.
> 
> Probably very related but I've opened #512 due to the same issue you're mentioning.
> 
> In my case `require_tool` is set to `false` though.

This is also the case with me

**Comment by Xanderasp** [comment]
https://github.com/FTBTeam/FTB-Mods-Issues/issues/512#issuecomment-1295389422
