### ISSUE TITLE
[Bug]: Cannot empty Pump using Fluid Cells

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Mods-Issues#337]
### Mod

FTB Industrial Contraptions

### Mod version

1.18 dev environment

### Forge / Fabric version

40.1.51

### What issue are you having?

![image](https://user-images.githubusercontent.com/15698722/177037065-baa61755-9683-4bae-973e-03f8e1a81163.png)

This is the only slot that Fluid Cells can be inserted

### Steps to reproduce

Pump with Pump
Put Fluid Cell in slot

**Comment by aaronhowser1** [comment]
Buckets can also go into the slot, but nothing happens then either

**Comment by MichaelHillcox** [comment]
Fixed in both 1.18 & 1.19 (both should be on CF)

**Comment by CaszGamerMD** [comment]
unless I'm missing something this issue is back? im playing ATM7 to the sky, and i have the latest version, the pump takes fluid but wont put it into the fluid cell

**Comment by MichaelHillcox** [comment]
This issue is linked to the main issue #1658 and will be closed. Please refer to that issue for more details.
