### ISSUE TITLE
[Bug]: FTB Industrial Contraptions Transformer (EV) 

### ISSUE THREAD

**Issue by showater** [FTBTeam/FTB-Mods-Issues#343]
### Mod

FTB Industrial Contraptions

### Mod version

1802.1.6-build.182

### Forge / Fabric version

1.18.2-40.1.52-universal

### Modpack & version

Direwolf20 1.5.1 and 1.6.1

### What issue are you having?

I cant get the EV transformer to work. I get the error message below. 
[Server thread/WARN] [minecraft/LevelChunk]: Block entity ftbic:hv_transformer @ BlockPos{x=-654, y=116, z=-4741} state Block{ftbic:ev_transformer}[dark=false,facing=east] invalid for ticking:

### Crashlogs

N/A

### Steps to reproduce

Craft the highest tier transformer
Put power into it

**Comment by MichaelHillcox** [comment]
Pretty sure this has been fixed for both 1.19 & 1.18, please reopen if this is still an issue on the latest version of the mod

**Comment by showater** [comment]
I believe 1802.1.6-build182 is the newest MC 1.18 version.  
I just updated the direwolf version to 1.7.0 and it still doesn't work.

**Comment by showater** [comment]
> Pretty sure this has been fixed for both 1.19 & 1.18, please reopen if this is still an issue on the latest version of the mod

I believe 1802.1.6-build182 is the newest MC 1.18 version.
I just updated the direwolf version to 1.7.0 and it still doesn't work.

**Comment by MichaelHillcox** [comment]
Should be fixed as of https://github.com/FTBTeam/FTB-Industrial-Contraptions/commit/28e34fbf2803bf61b981cc16caa1bba7df06ea1c

**Comment by DamondSword2247** [comment]
I still having this issue with the ftb-industrial-contraptions-1802.1.6-build.220.jar version of the mod. My reactor produces 3250 zaps p/t which is in the threshold of the EVs 8000 zaps p/t or so range but the transformer does absolutely nothing unless its below 1900 zaps p/t. I'm playing on FTB Inferno 1.6.1 so I don't know how it effects anything but I'm pretty sure it should still work even if I wasn't.
